### PR TITLE
Enable Selinux Enforcing

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Enable SELinux Enforcing](https://trello.com/c/WlALaNKE/930-enable-selinux-enforcing)

**Review by ramereth — APPROVED** [review]
Please do a minor bump.

**Comment by zimmerry** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.8.0.  Have a nice day!

**Pull request merged**
