### PR TITLE
Added almalinux 9

### PR DESCRIPTION
**Pull request by sharoninator**

### CODE REVIEW

**Comment by sharoninator** [comment]
Everything works fine out of the box! The recipes converge and pass all integration and spec tests.

**Review by ramereth — CHANGES_REQUESTED** [review]
Please add AlmaLinux 9 to spec testing (see `spec/spec_helper.rb`)

**Review by ramereth — APPROVED** [review]

**Comment by ramereth** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.12.1.  Have a nice day!

**Pull request merged**
